### ISSUE TITLE
企画一覧へ模擬授業・公開研究室の情報追加

### ISSUE THREAD

**Issue by minusvoid** [kougakusai/kougakusai-hp2022#104]
[模擬授業・公開研究室の情報](https://ibarakiuniversity.sharepoint.com/:x:/r/sites/msteams_06de47-2/Shared%20Documents/%E3%83%9B%E3%83%BC%E3%83%A0%E3%83%9A%E3%83%BC%E3%82%B8%E7%8F%AD/%E4%BC%81%E7%94%BB/%E4%BC%81%E7%94%BB%E4%B8%80%E8%A6%A7.xlsx?d=w08d16bd290e64260a4d90371cdeee25e&csf=1&web=1&e=TcYZ6G)が未入力なので、`/data/program/program.tsx`へ入力する

**Comment by fujitargz** [comment]
教室名は末尾に「室」を付ける（例：E3棟401室）

模擬授業・研究室公開で分けるのは OK だが、その中でも学科は分かるようにする
模擬授業の正確な時間は調整中なので記載なしで良い（決まり次第追加）
模擬授業は場所も調整中なので決まり次第追加
