### ISSUE TITLE
更新時にエラーが出る

### ISSUE THREAD

**Issue by ujimattya** [kougakusai/kougakusai-hp2022#112]
## 症状
TOPページ以外で更新を行うとエラーになります。
<img width="528" alt="CleanShot 2022-09-27 at 19 58 14@2x" src="https://user-images.githubusercontent.com/53252847/192508190-6b52eaab-c34e-4919-890f-2492991a1bd3.png">

## 原因
不明。SSGなので最初にTOPに行った時に他のページは受け取っているからリクエストせずに遷移している。更新してしまうと改めてそのページのURLでGETするのでTOP以外のパスは権限がなくてエラーが出ているのでは。
サーバー側で全てのページのパス（ファイル）に関して許可して貰えばいい？

**Comment by fujitargz** [comment]
確かに Web サーバの設定っぽいですね...

サーバ管理者の方に問い合わせて、そちらで対応できるのであればそれに従いましょう。
HP で使いたいパスを全て教えてくれ、と言われる可能性があると思うのでそれだけ準備する必要がありそうですね。

対応のためにこちら（ソースコード）で何か作業しなければならない場合は Issue に追記をお願いします。
（逆にサーバ管理者側だけで対応が完結したのであればこちらに詳細は書かずに Close で）

**Comment by fujitargz** [comment]
`/about`、`/program`ではリロードすると`/about/`、`/program/`になり403になる。
`/access`、`/contact`、`/site-policy`、`privacy-policy`ではリロードするとパスはそのままで404になる。
404ページは Next.js のものではない。
