### ISSUE TITLE
学校企画追加

### ISSUE THREAD

**Issue by fujitargz** [kougakusai/kougakusai-hp2022#119]
日立二高のステージ企画を追加

ただし時間は調整中なので記載しない

**Comment by minusvoid** [comment]
企画ファイルには、ステージ企画とは明記されていませんが、場所はステージで合っていますか？

**Comment by fujitargz** [comment]
はい。
確かに明記されていませんが、ステージ企画と聞いていますのでステージ開催と思われます。
