### ISSUE TITLE
企画一覧カテゴリ並べ替え

### ISSUE THREAD

**Issue by fujitargz** [kougakusai/kougakusai-hp2022#137]
企画一覧のカテゴリを以下の順に並べ替える（必要であれば名前も変更する）。

* 学生企画
* 教員企画
* 地元企画
* 模擬授業
* 研究室公開

ただし、カテゴリ内の企画の順番は並べ替えなくて良い。

**Comment by minusvoid** [comment]
### カテゴリ再編について

`学生企画` = `委員会`+`学内`+`技術部`
`地元企画` = `学校`+`多賀工業会（未達）`
の認識で良いですか？

**Comment by fujitargz** [comment]
振り分けについては @ga11o がお詳しいので確認をお願いします。

模擬授業・研究室公開については、少なくとも学科が区別できるように、との指示があったため現在のようになっています。そのため、現在のままで問題ありません。
模擬授業などで`section`にまとめるならその中で学科単位でサブセクションを切らないと要件を満たせないですね。

**Comment by ga11o** [comment]
@minusvoid
その認識で問題ありません。
