### ISSUE TITLE
iPhone で URL コピーボタンが表示されない

### ISSUE THREAD

**Issue by fujitargz** [kougakusai/kougakusai-hp2022#161]
#136 のレイアウト崩れは修正されたが、コピーボタンが見えないそうです。
ボタン自体は存在していて、それらしい場所をタップするとポップアップメッセージは出るとのこと。

**Comment by minusvoid** [comment]
> `iPhone`で

というのは、`iOS`の`Safari`ブラウザで、という認識で合っていますか？

**Comment by fujitargz** [comment]
聞きそびれたので @ga11o に確認していただきたく...（すみません）
