### ISSUE TITLE
こうがく祭当日以降のカウントダウンの値

### ISSUE THREAD

**Issue by fujitargz** [kougakusai/kougakusai-hp2022#185]
こうがく祭当日以降カウントダウンの値が`00`になるのか、いつから`00`になるのか、などを検証し、必要であれば修正を行う。
（特に JS で負の数の除算をした場合の仕様が関わってくると思われる）

https://github.com/kougakusai/kougakusai-hp2022/blob/5ad1ed047f16c751e46ecce6e1f7b1484e57cf5c/src/hooks/useCountDown/useCountDown.ts#L10-L13

**Comment by nomintense** [comment]
以下検証結果です
・issue43の方にも書きましたが、プログラム内では開催時刻が11月5日0時と設定されており、時間の切り捨てが行われるため、11月4日になった直後にHPを開くと「開催まで残り0日」と表示されます。（なので前日にHPを開くと困った事になるため近いうちに修正します）
・開催日以降はずっと「開催まで残り0日」と表示されます

**Comment by fujitargz** [comment]
終了後の内容は #200 で実装したため close
