### ISSUE TITLE
LinkButton実装

### ISSUE THREAD

**Issue by fujitargz** [kougakusai/kougakusai-hp2022#28]
# 概要
「お知らせ」の「もっと見る」などで使用する`LinkButton`を実装する。

# 詳細
* 「お知らせ」の「もっと見る」、フッタの「お問い合わせ」で使用
* 矢印はアイコンライブラリの画像などを使用
* `next/link`で遷移できるようにする

# 実装先
`src/components/Button/LinkButton/LinkButton.tsx`

**Comment by minusvoid** [comment]
「もっと見る」・「お問い合わせ」は`props`で入力するか、`props`で選択させる（`type=detail | ask`）か、2つに分けるかどうしますか？

**Comment by fujitargz** [comment]
リンク先とテキストは使うときに`props`で入力でお願いします（他のコンポーネントとちょっと違うインターフェースになってしまいますが）。
それと、詳しく見るボタンで設計をミスったなと思った点ですが、テキストは`children`にするのが自然でした。
実装上の問題がなければ`children`をテキストにすると良いかと思います。
