### ISSUE TITLE
Storybook使用中`/public`以下のファイルが読み込めない

### ISSUE THREAD

**Issue by minusvoid** [kougakusai/kougakusai-hp2022#36]
- 問題

Storybook使用中に`<img>`などで`/public`にある画像が表示されない

- 解決法

`.storybook/main.js`へ
``` main.js
staticDirs: ['../public'],
```
を追記する

**Comment by fujitargz** [comment]
後出し告知で大っっ変申し訳ないのですが、画像は`next/image`なら表示できますか？

`next/image`なら`basePath`の反映（去年はいちいち`basePath+'path/to/image.png'`みたいな感じでやっていたところ）とかをよしなにやってくれる、かつ、公式から（ experimental だけど）`next/image`を`next export`でも使えるようにする設定が提供されたので、今年は`next/image`を使えるように設定しています。

`src/pages/index.tsx`と`src/stories/images.stories.tsx`で使用しているので、そちらの方法を一度試していただきたいです。
