### ISSUE TITLE
メニューボタン実装

### ISSUE THREAD

**Issue by fujitargz** [kougakusai/kougakusai-hp2022#6]
# 概要
画面右上（ヘッダ右端）のメニューボタンを実装する。

# 詳細
* 背景は透過
* 枠線まで実装する
* 画像は`public/rhino_soldering.png`
* スタイルはデザインデータ参照のこと
* クリックできるボタンとして実装する
* クリック時の動作は`onClick`で受け取れるよう実装する
* `className`も受け取れると良い

# 実装先
`src/components/Button/MenuButton/MenuButton.tsx`

**Comment by ayagifc** [comment]
@fujitargz 
実装の仕方について質問です。
背景の透過とありますが、画像自体に背景が含まれています。
その場合でも実装側の処理だけで透過することが可能なのでしょうか？

**Comment by fujitargz** [comment]
画像部分は実装側ではどうにもならないので、画像の背景はそのままで問題ありません。

**Comment by fujitargz** [comment]
PC版デザインが出ているので、そちらの対応もお願いします。
（後出しで申し訳ありません）
