### ISSUE TITLE
スクロール機能実装

### ISSUE THREAD

**Issue by fujitargz** [kougakusai/kougakusai-hp2022#80]
トップページの詳しく見るボタン押下時にお知らせまでスクロールする機能を実装する。
カスタムフックとして提供できると良い。

**Comment by minusvoid** [comment]
### ページ内スクロール（アンカーリンク）について
それ自体はスクロール対象の`id`を`href`に設定すればできるので、カスタムフックにするまでもなく簡単だと思います。

```e.g.
...
<a href="#TARGET_ID">ターゲットまでスクロール</a>
...
<element id="TARGET_ID" />
...
```

### 問題

- `a`タグで動作させるのが簡単（逆に`onClick`実装は結構大変）なので、`Rounded Button`の構造を変える（か、`a`で囲む）必要がある（`a11y`的にも`a`を使うのがよい）

- `html`タグなどに`scroll-behavior: smooth;`を指定するとスムーズスクロール（アンカーリンクでスクロールアニメーションが流れる）になるはずだが、手元で試した感じうまく動作しない
ので、`js`で実装するか結構試行錯誤するかスムーズスクロールをあきらめる必要がある

**Comment by fujitargz** [comment]
調査ありがとうございます！

`<a>`で実装する方針で動作するのであればその方針で構いません(`RoundedButton`の修正をしても構いません)。
手元に PC が無いので`scroll-behavior`の確認はできません、情報提供できずすみません…

余談ですがこの Issue を立てるにあたって軽くググったところ`scrollIntoView`を使った実装が多かったので、`ref`とスクロールを発火する関数を返すカスタムフックになるのかなー、と思いカスタムフックと書いた次第です。
