### ISSUE TITLE
詳しく見るボタンの実装

### ISSUE THREAD

**Issue by fujitargz** [kougakusai/kougakusai-hp2022#9]
# 概要
ランディング部分（トップページのお知らせより上の領域）の「詳しく見る」ボタンを実装する。

# 詳細
* 矢印アイコンはアイコンライブラリの画像やCSSで対応する
* `text`、`disabled`、`onClick`、`className`を受け取れるように実装する
  * ボタンのテキストを`text`に渡す
  * `disabled`のデフォルト値は`false`で、`true`の時のみボタンを`disabled`にする
  * `onClick`にはボタンクリック時の処理を渡す
* スタイルはデザインデータ参照のこと

# 実装先
`src/components/Button/RoundedButton.tsx`

**Comment by fujitargz** [comment]
設計を変更した方が良さそう。
`sm`の動作はリンクで決打ちしてしまって良いが`lg`の動作は外部から指定したい(スクロール)。
`ScrollButton`と`LinkButton`に分ける？

**Comment by fujitargz** [comment]
仕様変更。`RoundedButton`と`LinkButton`に分け、この Issue では`RoundedButton`のみ実装する。

**Comment by fujitargz** [comment]
PC版デザインが出ているので、そちらの対応もお願いします。
（後出しで申し訳ありません）

**Comment by minusvoid** [comment]
各ボタンの名称がFigmaで指しているものを確認したいです。

- `sm`Button：スマホビュー（細長くて最初からある）の黄色背景「詳しく見る」
- `lg`Button：デスクトップビュー（右側）の黄色背景「詳しく見る」の見た目・サイズ
- `RoundedButton`：`active`で所定の要素までスクロールする動作のボタン（スマホビューの黄色背景「詳しく見る」ボタン？）
- `LinkButton`：`active`で別ページへ遷移する動作のボタン（スマホビューの背景無「もっと見る」ボタン？）

今回作成するボタンが、**低級のコンポーネント**で、`text`・`onClick`を受け取るものならば、ただの角丸ボタンかつレスポンシブサイズ対応で、背景指定もなしで、高階級でこのコンポーネントに背景色や動作をつけるのが自然な感じがします。

**Comment by fujitargz** [comment]
`sm`と`lg`は仕様変更前の話なので忘れていただきたく。
仕様変更前は`RoundedButton`と`LinkButton`を同じコンポーネントにして、`props`の`size`が`sm`か`lg`かで出し分ける、という設計にしていたので、それを指していました。

> * `RoundedButton`：`active`で所定の要素までスクロールする動作のボタン（スマホビューの黄色背景「詳しく見る」ボタン？）
> * `LinkButton`：`active`で別ページへ遷移する動作のボタン（スマホビューの背景無「もっと見る」ボタン？）

`RoundedButton`と`LinkButton`の認識は上記で問題ありません。
ただし、現時点では`RoundedButton`にスクロール機能までは持たせなくて良いです。
ランディング実装時点ではスクロールが必要ないこと、スクロール機能の実装がどうなるか不明なこと、が理由です。
（おそらく「お知らせ」に`ref`を設定して`ref.current.scrollIntoView()`を呼ぶ形になるのでそもそも現時点で実装するのは難しいかと）
